language: cpp

compiler: gcc

before_install:
  - sudo apt-add-repository ppa:beineri/opt-qt541 -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt54-meta
  - sudo /opt/qt54/bin/qt54-env.sh

before_script:
  - mkdir build
  - cd build
  - qmake ..

script: make

branches:
  only:
    - master

matrix:
  fast_finish: true
